### ISSUE TITLE
Naming things is hard!

### ISSUE THREAD

**Issue by ryangribble** [mirsaeedi/octokit.net.extensions#2]
Given that the main Octokit.net library is actually called Octokit [on nuget](https://www.nuget.org/packages/Octokit/) and not octokit.net, I think this library should be `Octokit.Extensions` rather than `octokit.net.Extensions`.  I also think you should follow the main libraries sentence casing, eg `Octokit.Extensions` rather than lowercase `octokit` and uppercase `Extensions`.

This renaming should be done on everything including the folders/file names, project name, namespaces, nuget package name and of course the github repo itself!

**Comment by mirsaeedi** [comment]
What about keeping the GitHub repo name as "octokit.net.extensions". Because, the Octokit's GitHub repo name is "octokit.net"

**Comment by ryangribble** [comment]
Ah yes very true!
